# Generated by Django 6.1 on 2026-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("web-development", "Web Development"),
                            ("software-development", "Software Development"),
                            ("mobile-development", "Mobile Application Development"),
                            ("it-support", "IT Support"),
                            ("networking", "Networking"),
                            ("business-solutions", "Business Solutions"),
                            ("consulting", "Technology Consulting"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under-5000", "Below K5,000"),
                            ("5000-10000", "K5,000 - K10,000"),
                            ("10000-25000", "K10,000 - K25,000"),
                            ("25000-50000", "K25,000 - K50,000"),
                            ("50000-plus", "Above K50,000"),
                            ("not-sure", "Not Sure Yet"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
