# Generated by Django 6.1 on 2026-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="NetCore TECH Solutions", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Connecting technology, empowering businesses.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Technology that moves your business forward.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="We build practical digital solutions that help businesses work smarter, operate efficiently and grow."
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "footer_description",
                    models.TextField(
                        default="Connecting technology, empowering businesses. We build practical digital solutions for modern organizations."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
