# Generated by Django 6.1 on 2026-08-25 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="NetCore TECH Solutions", max_length=200),
                ),
                (
                    "short_intro",
                    models.TextField(
                        default="NetCore TECH Solutions is a technology-focused company providing practical digital and IT solutions for modern businesses and organizations."
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                    ),
                ),
                (
                    "our_story",
                    models.TextField(
                        blank=True,
                        help_text="The main story and background of the company.",
                    ),
                ),
                (
                    "why_we_started",
                    models.TextField(blank=True, help_text="Why NetCore was created."),
                ),
                (
                    "problem_we_wanted_to_solve",
                    models.TextField(
                        blank=True,
                        help_text="The problem or gap NetCore wanted to address.",
                    ),
                ),
                (
                    "how_we_started",
                    models.TextField(
                        blank=True, help_text="Describe how NetCore started."
                    ),
                ),
                (
                    "initial_services",
                    models.TextField(
                        blank=True, help_text="Services NetCore initially offered."
                    ),
                ),
                (
                    "how_we_have_grown",
                    models.TextField(
                        blank=True,
                        help_text="Describe the growth and development of NetCore.",
                    ),
                ),
                (
                    "who_we_are",
                    models.TextField(
                        blank=True,
                        help_text="Professional description of who NetCore is.",
                    ),
                ),
                (
                    "what_we_do",
                    models.TextField(
                        blank=True, help_text="Describe what NetCore does."
                    ),
                ),
                (
                    "what_makes_us_different",
                    models.TextField(
                        blank=True,
                        help_text="What makes NetCore different from other companies.",
                    ),
                ),
                (
                    "future_goals",
                    models.TextField(
                        blank=True, help_text="Where NetCore wants to go in the future."
                    ),
                ),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Profile",
                "verbose_name_plural": "About Profile",
            },
        ),
        migrations.CreateModel(
            name="CompanyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name or symbol.",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Company Value",
                "verbose_name_plural": "Company Values",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(
                        help_text="Example: Founder & Managing Director", max_length=200
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="Example: IT Specialist, Software Developer",
                        max_length=200,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "short_bio",
                    models.TextField(
                        blank=True, help_text="Short professional biography."
                    ),
                ),
                (
                    "professional_background",
                    models.TextField(
                        blank=True, help_text="Professional background and experience."
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Relevant educational background."
                    ),
                ),
                (
                    "professional_skills",
                    models.TextField(
                        blank=True,
                        help_text="Professional skills and areas of expertise.",
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leadership Profile",
                "verbose_name_plural": "Leadership Profiles",
                "ordering": ["display_order", "full_name"],
            },
        ),
    ]
