# Generated by Django 6.1 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "short_description",
                    models.TextField(
                        help_text="Short description displayed on the services page.",
                        max_length=400,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Full description of the service."),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("digital", "Digital Solutions"),
                            ("software", "Software Development"),
                            ("infrastructure", "IT & Infrastructure"),
                            ("consulting", "Technology Consulting"),
                        ],
                        default="digital",
                        max_length=30,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name or identifier.",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Separate technologies with commas.",
                        max_length=500,
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Enter one feature per line."
                    ),
                ),
                (
                    "process",
                    models.TextField(
                        blank=True, help_text="Enter one process step per line."
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional starting price in Zambian Kwacha.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "-featured", "-created_at"],
            },
        ),
    ]
