# Generated by Django 6.1 on 2026-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short description displayed on the blog listing.",
                        max_length=500,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("web", "Web Development"),
                            ("software", "Software Development"),
                            ("networking", "Networking"),
                            ("it-support", "IT Support"),
                            ("business", "Business Technology"),
                            ("news", "Company News"),
                            ("tutorial", "Tutorial"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "author",
                    models.CharField(default="NetCore TECH Solutions", max_length=150),
                ),
                ("featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-featured", "-published_at", "-created_at"],
            },
        ),
    ]
