# Generated by Django 6.1 on 2026-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(max_length=500),
        ),
    ]
