# Generated by Django 6.1 on 2026-08-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("short_description", models.TextField(max_length=500)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("software", "Software Development"),
                            ("networking", "Networking"),
                            ("it", "IT Solutions"),
                            ("mobile", "Mobile Application"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=200)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Separate technologies with commas.",
                        max_length=500,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                ("project_url", models.URLField(blank=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-featured", "-completed_date", "-created_at"],
            },
        ),
    ]
