# Generated by Django 6.1 on 2026-08-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("software", "Software Development"),
                            ("mobile", "Mobile Application"),
                            ("networking", "Networking"),
                            ("it-support", "IT Support"),
                            ("education", "Education Technology"),
                            ("business", "Business Solution"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=30,
                    ),
                ),
                ("short_description", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("client", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("ongoing", "Ongoing"),
                            ("maintenance", "Maintenance"),
                            ("concept", "Concept"),
                        ],
                        default="completed",
                        max_length=30,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio/projects/"
                    ),
                ),
                ("challenge", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("results", models.TextField(blank=True)),
                (
                    "technologies",
                    models.TextField(
                        blank=True,
                        help_text="Enter technologies separated by commas. Example: Django, Python, Tailwind CSS, SQLite",
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Enter major features separated by commas.",
                    ),
                ),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Project",
                "verbose_name_plural": "Portfolio Projects",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/screenshots/")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Screenshot",
                "verbose_name_plural": "Project Screenshots",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project Technology",
                "verbose_name_plural": "Project Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
