# Generated by Django 6.1 on 2026-08-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        help_text="Full name of the client.", max_length=150
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Company or organization name.",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Client's position or professional title.",
                        max_length=150,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional client profile photo.",
                        null=True,
                        upload_to="testimonials/",
                    ),
                ),
                (
                    "testimonial",
                    models.TextField(help_text="The client's testimonial."),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "5 Stars"),
                            (4, "4 Stars"),
                            (3, "3 Stars"),
                            (2, "2 Stars"),
                            (1, "1 Star"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="Service the client received.",
                        max_length=200,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Display this testimonial prominently."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Make this testimonial visible on the website.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["display_order", "-featured", "-created_at"],
            },
        ),
    ]
